# Generated by Django 3.0.3 on 2020-02-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0006_auto_20200218_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupForm',
        ),
    ]
