# Generated by Django 3.0.3 on 2020-02-20 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0009_auto_20200220_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinForm',
        ),
    ]
