# Generated by Django 3.0.3 on 2020-02-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0011_joinform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinform',
            name='mtel',
            field=models.IntegerField(blank=True),
        ),
    ]
