# Generated by Django 3.0.3 on 2020-02-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0013_horse_mypick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horse',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='MyPick',
            new_name='Survey',
        ),
    ]
