# Generated by Django 3.0.3 on 2020-02-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0014_auto_20200228_1806'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Horse',
        ),
        migrations.RenameModel(
            old_name='Survey',
            new_name='MyPick',
        ),
    ]
