# Generated by Django 3.0.3 on 2020-02-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0015_auto_20200228_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypick',
            name='ans62',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans63',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans65',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans66',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans67',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans68',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans69',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans70',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans71',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans72',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans73',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans74',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans75',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans76',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans77',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mypick',
            name='ans78',
            field=models.TextField(null=True),
        ),
    ]
