# Generated by Django 3.0.3 on 2020-03-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0016_auto_20200228_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyPick',
            new_name='Select',
        ),
    ]
