# Generated by Django 3.0.2 on 2020-01-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile1',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(null=True)),
                ('skills', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.TextField(null=True)),
                ('regdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
