# Generated by Django 3.0.2 on 2020-01-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(),
        ),
    ]
