# Generated by Django 3.0.2 on 2020-01-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200109_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
